# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x07\x65xample\x1a\x1cgoogle/api/annotations.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2_\n\x0cHelloService\x12O\n\x08SayHello\x12\x15.example.HelloRequest\x1a\x16.example.HelloResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\"\t/v1/hello:\x01*b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOSERVICE'].methods_by_name['SayHello']._loaded_options = None
  _globals['_HELLOSERVICE'].methods_by_name['SayHello']._serialized_options = b'\202\323\344\223\002\016\"\t/v1/hello:\001*'
  _globals['_HELLOREQUEST']._serialized_start=54
  _globals['_HELLOREQUEST']._serialized_end=82
  _globals['_HELLORESPONSE']._serialized_start=84
  _globals['_HELLORESPONSE']._serialized_end=116
  _globals['_HELLOSERVICE']._serialized_start=118
  _globals['_HELLOSERVICE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
